### ISSUE TITLE
How to sand bushing

### ISSUE THREAD

**Issue by astorch98** [AguaClara/float_valve#21]
1. PVC glue with sand paper around pvc pipe
2. PVC glue/ adhesive on pipe and dip it in sand
3. Heating pipe, sticking it through bushing, then adding sand/sandpaper

**Comment by astorch98** [comment]
2. Failure (partly because glue was clumpy)

**Comment by ethan92429** [comment]
I've done this multiple times. The first step is to cut the bushing so that it is a small fraction of the original depth. Cut it so that the the external lip is still part of the bushing. But the bushing can be very thin - more like a disk. Thinner helps both because near the top, the bushing is larger, and so there is less friction between the sliding tube and the bushing, and second because a thinner bushing means a larger vertical distance that the sliding pipe is exposed - and thus more efficient use of vertical space. Here's a pic of how to cut:
![cut_the_bushing](https://user-images.githubusercontent.com/8585379/36870846-5a47daf4-1d6e-11e8-854e-7496ae599cde.PNG)

**Comment by ethan92429** [comment]
You need just enough length so that the glue can hold the bushing in well.

**Comment by FelixYuHengYang** [comment]
[https://photos.google.com/photo/AF1QipOcw29V5IkFWs-U1G3CLXcmdEmgVZ8Nm5XoU0nL](url)
[https://photos.google.com/photo/AF1QipNQrz_OHAz_Uvq9pD-Ee_6CXo5rT9gTcRD2R4uf](url)

**Comment by FelixYuHengYang** [comment]
![img_20180301_184313](https://user-images.githubusercontent.com/31310824/36877502-887d1ece-1d88-11e8-9119-6d205a2453b1.jpg)
![img_20180301_184528](https://user-images.githubusercontent.com/31310824/36877503-888869dc-1d88-11e8-9a30-9b2a95ff027f.jpg)
