### ISSUE TITLE
More design questions

### ISSUE THREAD

**Issue by FelixYuHengYang** [AguaClara/float_valve#6]
Does water necessarily have to come out of the bottom? Will we need to install weights so that the float valve doesn't ever get stuck?

**Comment by FelixYuHengYang** [comment]
Elaborating more on the first question... 

If we plug the bottom and water only comes out of the drilled holes does that affect the function of the float valve?

**Comment by FelixYuHengYang** [comment]
We were thinking that we could avoid using a T at the bottom and instead use that part of the pipe below the holes as a column to hold weight. This would both serve as a weight and avoid using a T that is pretty expensive at that scale.

**Comment by ethan92429** [comment]
I like this idea! however, if you want to maximize the travel of the pipe, then the pipe shouldn't have much of a dead zone. Maybe you could just put a cap in the end and throw some biggish rocks down? That way you could still drill holes all the way to the bottom and water flows around the rocks to get out... No need to have a tee at the bottom. Also no need to have a tee for the float... depending on what you calculate for a required volume for that, you could maybe just use a 6" ND hole saw and pass a 6" pipe all the way through (I know accessories can get expensive at these sizes!)

**Comment by FelixYuHengYang** [comment]
Okay we will go with cap and hole idea as well as no T for the top part of the float. Another question... 
How did you determine the hole pattern in the slider pipe?

**Comment by FelixYuHengYang** [comment]
When you get to that plant could you mesaure what is the height at which the center of inlet pipe enters the tank measured from the bottom of the tank?

**Comment by ethan92429** [comment]
I did not spend any time in thinking about the hole pattern. My two observations: 
1. radially symmetric holes are good... they aren't inclined to tilt the sliding pipe to one side or the other
2. you want a gradual increase/decrease. Make sure that the "sliding window" of the inlet pipe tee doesn't expose large swings in flow rate. It will to some degree, unless you always space holes at a factor's spacing away from another, where the "factor" is a factor of the total sliding window height... this makes more sense visually. Such that as one hole closes, the other opens, so that one "completes" the other. 

I can measure that when I get there!
